#!/bin/sh
set -eu

guest=/usr/lib/arlinux/guest
command=${1:-}
case "$command" in
    dump)
        shift
        exec python3 "$guest/dump-atspi.py" "$@"
        ;;
    click|type|set)
        shift
        exec python3 "$guest/atspi-do.py" "$command" "$@"
        ;;
    *)
        echo 'usage: arlinux-a11y dump [APP]' >&2
        echo '       arlinux-a11y click NEEDLE [APP]' >&2
        echo '       arlinux-a11y type TEXT [APP]' >&2
        echo '       arlinux-a11y set TEXT [APP]' >&2
        exit 2
        ;;
esac
